# Generated by Django 5.1.6 on 2025-03-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_image",
            field=models.ImageField(blank=True, default="", null=True, upload_to=""),
        ),
    ]
