# Generated by Django 5.1.6 on 2025-03-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_singer_points_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='singer_image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
