# Generated by Django 5.1.6 on 2025-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singer",
            name="singer_image",
            field=models.ImageField(
                blank=True,
                default="C:\\Users\\MK\\Downloads\\fanta-builder\\uploads/unknown.svg",
                null=True,
                upload_to="",
            ),
        ),
    ]
