# Generated by Django 5.1.6 on 2025-04-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_singer_singer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singer",
            name="singer_image",
            field=models.ImageField(
                blank=True, default="/unknown.svg", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_image",
            field=models.ImageField(
                blank=True,
                default="C:\\Users\\MK\\Downloads\\fanta-builder\\uploads/unknown.svg",
                null=True,
                upload_to="",
            ),
        ),
    ]
