# Generated by Django 5.1.6 on 2025-03-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_singer_singer_image_alter_team_team_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team", "singer")},
        ),
    ]
