# Generated by Django 5.1.6 on 2025-03-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_remove_teammember_added_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="user_id",
            new_name="user",
        ),
    ]
