# Generated by Django 5.1.6 on 2025-03-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0008_alter_team_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="captain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teams.singer",
            ),
        ),
    ]
