# Generated by Django 5.1.6 on 2025-03-16 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0009_team_captain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singer",
            name="points_cost",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(80),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="singer",
            name="singer_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
