# Generated by Django 5.1.6 on 2025-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="C:\\Users\\MK\\Downloads\\fanta-builder\\uploads/unknown.svg",
                null=True,
                upload_to="",
            ),
        ),
    ]
