# Generated by Django 5.1.6 on 2025-03-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
