# Generated by Django 5.1.6 on 2025-03-04 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="teams_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
