# Generated by Django 5.1.6 on 2025-03-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_teams_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
