# Generated by Django 5.1.6 on 2025-03-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, default="/unknown.svg", null=True, upload_to=""
            ),
        ),
    ]
