# Generated by Django 5.1.6 on 2025-04-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='event',
        ),
        migrations.CreateModel(
            name='MemberOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.event')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.occurrence')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teammember')),
            ],
            options={
                'unique_together': {('occurrence', 'event', 'team_member')},
            },
        ),
    ]
