# Generated by Django 5.1.6 on 2025-03-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='occurrence',
            name='outcome',
            field=models.CharField(choices=[('BONUS', 'Bonus'), ('PENALTY', 'Penalty')], default='BONUS', max_length=10),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.event'),
        ),
    ]
