# Generated by Django 5.1.6 on 2025-04-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_remove_occurrence_event_memberoccurrence"),
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingerOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rules.event"
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules.occurrence",
                    ),
                ),
                (
                    "singer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.singer"
                    ),
                ),
            ],
            options={
                "unique_together": {("singer", "occurrence", "event")},
            },
        ),
    ]
