# Generated by Django 5.1.6 on 2025-04-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0003_singeroccurrence"),
    ]

    operations = [
        migrations.RenameField(
            model_name="occurrence",
            old_name="occurence",
            new_name="occurrence",
        ),
    ]
