# Generated by Django 5.1.6 on 2025-04-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_rename_occurence_occurrence_occurrence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberOccurrence',
        ),
    ]
